### ISSUE TITLE
Use Management Client 

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-generators-net#124]
Instead of using a manual client - it would be great to use client from  [`Kentico.Kontent.Management` nuget](Kentico.Kontent.Management).

https://github.com/Kentico/kontent-generators-net/blob/338f8944b4d20adb5b46e67047c892977be3789b/src/Kentico.Kontent.ModelGenerator.Core/ManagementClient/ManagementClient.cs#L15

Related to #117

**Comment by Simply007** [comment]
As a part of issue - fix also namespace (ManagementClientImpl vs. ManagementClient) - see https://github.com/Kentico/kontent-generators-net/pull/117/commits/338f8944b4d20adb5b46e67047c892977be3789b:

https://github.com/Kentico/kontent-generators-net/blob/338f8944b4d20adb5b46e67047c892977be3789b/test/Kentico.Kontent.ModelGenerator.Tests/CodeGeneratorIntegrationTests.cs#L15

Look for another usages like this.

**Comment by Sevitas** [comment]
Can be resolved after [https://github.com/Kentico/kontent-management-sdk-net/issues/53](https://github.com/Kentico/kontent-management-sdk-net/issues/53)
