### ISSUE TITLE
Generate IEnumerable<SpecificType> for linked items elements with constraint

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-generators-net#17]
**Blocked:** We need the content type API endpoint to return the information about content element constraints

### Motivation

If a linked items element is [limited](https://kenticocloud.com/blog/kentico-cloud-product-launch-april-2017) to accept only items of specific types, we should be able to reflect that in generated models. 

### Design guidelines

If it is constrained to a single content type, we should be able to generate its property as `IEnumerable<SpecificType>` instead of `IEnumerable<object>`. If the element is constrained to several content types, we could somehow allow the developer to associate the property with an [interface](https://github.com/Kentico/cloud-generators-net/issues/24), which would make the generator always create the property of type `IEnumerable<Interface>`.

**Comment by hades200082** [comment]
You could do this for all types.

Define an interface - something like `IListableObject` and set that in the IEnumerable.  Then just have all generated models implement that interface.

A method of the interface (and thus generated in each class - or using a base abstract class) could return a properly cast object based on the `system.type` property. (e.g. `myListableObject.AsType()` )

**Comment by petrsvihlik** [comment]
The content items in `IEnumerable<object>` are already strongly typed.
So you can do e.g.

```
public IEnumerable<object> ModularContentItems {get;set;}

...
var articles = ModularContentItems.OfType<Article>();
```

I would rather not introduce any more complexity to the type system. (And one thing we wanted to avoid from the beginning is inheritance - we wanted POCO models.) You can extend the existing models by using partial classes (if you want) but this is not something we should generate by default. Or do you think otherwise?

**Comment by petrsvihlik** [comment]
duplicate of #90 

best practice: https://github.com/Kentico/kontent-generators-net/blob/master/README.md#handling-content-element-constraints
