### ISSUE TITLE
Fix IL Linker

### ISSUE THREAD

**Issue by petrsvihlik** [Kentico/kontent-generators-net#41]
The current publishing script:

`dotnet publish --framework netcoreapp2.0 --runtime win7-x64 -o ..\..\artifacts /p:ShowLinkerSizeComparison=true /p:LinkDuringPublish=false`

-> `/p:LinkDuringPublish=false` The linking had to be disabled because of exceptions being thrown during runtime. Most likely it was not possible to load some types that are being accessed via reflection. E.g. Configuration - loaded via DI.

It should be possible to name assemblies that shouldn't be linked. 
```
<ItemGroup>
  <LinkerRootAssemblies Include="MyAssembly" />
</ItemGroup>
```
For more info please refer to the documentation: https://github.com/dotnet/announcements/issues/30

**Comment by JanLenoch** [comment]
I didn't reveal anything useful. Nihil novi sub sole. As you wrote, id crashes when accessing Configuration, at CloudModelGenerator.Program.CreateCodeGeneratorOptions(ArgumentSyntax argSyntax). There are no pending issues related to that problem neither in [mono/linker](https://github.com/mono/linker/issues) nor [dotnet/core](https://github.com/dotnet/core/issues) repos. As I couldn't determine any other details about what could have gone wrong, I haven't filed my own issue (yet).

Closing.
