### ISSUE TITLE
Duplicate partial class generated when using specific command line switches.

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-generators-net#92]
### Brief bug description

Using the following command line to generate my classes

```ps
dotnet tool restore
dotnet tool run KontentModelGenerator -p "xxxxxxxxxxxx" -o "..\Models\ContentTypes" -n "Test.Web.Models" -g -s -f "Generated" -b "ContentTypeBase"
```

When the classes are generated the Modelname.Generated.cs class gets generated with duplicate partials within ContentTypeBaseExtender.cs:

```cs
    public partial class BlockQuote : ContentTypeBase
    {
    }

    public partial class BlockQuote : ContentTypeBase
    {
    }
```

### Repro steps

1. See above.

### Expected behavior

Should only generate one set of partial classes in the ContentTypeBaseExtender.cs file.

### Test environment

Using latest .NET Core Kentico Boiler Plate template.

**Comment by petrsvihlik** [comment]
fixed in https://github.com/Kentico/kontent-generators-net/releases/tag/4.0.2
