### ISSUE TITLE
Deterministic output of generated models

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-generators-net#99]
### Motivation

When we re-generate models the generator seems to randomly order the properties in the model.

So even if the model had no changes, when you do a diff on one generated model compared to the previous they are different, even though they are the same.

See here for an example of a model that was re-generated using the beta-2 command line kontent generator.

During code reviews people will ask questions on why this was done. It also causes unnecessary noise during code reviews.

![image](https://user-images.githubusercontent.com/6610039/77662937-776b3880-6f4a-11ea-9df4-8c102664ea19.png)

### Proposed solution

Perhaps just sort all properties alphabetically is an easy fix for this issue. That way everything gets generated the same way all the time.

**Comment by petrsvihlik** [comment]
fixed in https://github.com/Kentico/kontent-generators-net/releases/tag/5.0.0-beta4

**Comment by xantari** [comment]
You guys rock! Thanks so much.
